//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoFileRenamer.Download
{
    using System;
    using System.Collections.Generic;
    
    public partial class Director
    {
        public Director()
        {
            this.Films = new HashSet<Film>();
        }
    
        public int IdDirector { get; set; }
        public string FistName { get; set; }
        public string SecondName { get; set; }
    
        public virtual ICollection<Film> Films { get; set; }
    }
}
