//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoFileRenamer.Download
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        public Film()
        {
            this.Genres = new HashSet<Genre>();
        }
    
        public int IdFilm { get; set; }
        public string Name { get; set; }
        public string OriginalName { get; set; }
        public int Year { get; set; }
        public int Director_id { get; set; }
        public string FileName { get; set; }
    
        public virtual Director Director { get; set; }
        public virtual ICollection<Genre> Genres { get; set; }
    }
}
