USE [master]
GO

/****** Object:  Database [Videos]    Script Date: 07.09.2014 22:11:21 ******/
CREATE DATABASE [Videos]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Videos', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Videos.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Videos_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Videos_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Videos] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Videos].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Videos] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Videos] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Videos] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Videos] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Videos] SET ARITHABORT OFF 
GO

ALTER DATABASE [Videos] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Videos] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Videos] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Videos] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Videos] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Videos] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Videos] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Videos] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Videos] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Videos] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Videos] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Videos] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Videos] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Videos] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Videos] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Videos] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Videos] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Videos] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Videos] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Videos] SET  MULTI_USER 
GO

ALTER DATABASE [Videos] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Videos] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Videos] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Videos] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Videos] SET  READ_WRITE 
GO


